### PR TITLE
Create zh.ts

### PR DESCRIPTION
**Pull request by David200308**
Who want to help me to fix some English to Chinese translate problem in here?
谁想帮我解决一些中文翻译的问题？

### CODE REVIEW

**Comment by Cobra-Bitcoin** [comment]
Thank you!

How confident are you about these translations? Is it good enough to put into the wallet?

**Comment by David200308** [comment]
I think 90% confident I have, also I think it is ok to put it into the wallet.

**Comment by David200308** [comment]
now I think it is ok to put

**Comment by Cobra-Bitcoin** [comment]
Thank you!

**Comment by David200308** [comment]
ok, Thanks

**Pull request merged**
