### PR TITLE
Create id.ts

### PR DESCRIPTION
**Pull request by eb-ina**
Indonesian Translations

### CODE REVIEW

**Comment by Cobra-Bitcoin** [comment]
Wow, this looks great, thank you so much for taking the time to translate into Indonesian!

I noticed you're missing a closing quote here:
https://github.com/bitcoin-dot-org/BitcoinWalletMobile/blob/44797ecbe9840eaf57dd86c47551ba2685eadc37/lang/id.ts#L42

**Comment by eb-ina** [comment]
> Wow, this looks great, thank you so much for taking the time to translate into Indonesian!
> 
> I noticed you're missing a closing quote here:
> https://github.com/bitcoin-dot-org/BitcoinWalletMobile/blob/44797ecbe9840eaf57dd86c47551ba2685eadc37/lang/id.ts#L42

ougghhh... missed that. Fixed now

**Comment by Cobra-Bitcoin** [comment]
Merged :)

**Comment by cacrowley** [comment]
bc644e1113da2da5a3f77838184579647bf32c65

**Pull request merged**
